### ISSUE TITLE
Cannot trap incorrect onewire sensor address

### ISSUE THREAD

**Issue by Farmer-Giles** [kipe/python-onewire#1]
When an incorrect onewire device address is used then AttributeError is never reached, as the self.attrs property appears to cause an infinite recursion spiral. See http://stackoverflow.com/questions/41086460/cannot-trap-python-exception-from-imported-module for more details. I have tried the fix suggested by Luke Woodward and this works for me and has got me out of a hole.

**Comment by kipe** [comment]
Wow!
Surprised even by someone using this library, as it's so incomplete :smiley:

I'll have to find time for checking this issue out and fixing it. Pull requests are very welcome in the meantime, as I'm not even actively using the library myself...

**Comment by Emantor** [comment]
The problem is this line of code:
```
self._attrs = self._ow.get(self.path).split(',')
```
in the attrs property. If the C-Library call returns None, the split function raises an AttributeError, calling in turn the `__getattr__` function which in turn calls the attrs property, resulting in an infinite recursion.
I'll add tests in an extra branch and will post a solution later.

**Comment by kipe** [comment]
Awesome :+1:
